### PR TITLE
Include original source in client-side error messages

### LINKED ISSUE #1184: [Bug]: Client Stylesheet parser blows up when using incorrect content type
### What happened?

Error in xcode: 

```
Stylesheet parsing failed for class `circle`:

error: multiple failures occurred

error: /Users/bcardarella/projects/lvn_demo/lib/lvn_demo_web/styles/thermostat_styles.ex:LvnDemoWeb.ThermostatStyles:6: No matching clause found for modifier 'background'. Expected one of `background(alignment:content:)`, `background(ignoresSafeAreaEdges:)`, `background(_:ignoresSafeAreaEdges:)`, `background(in:fillStyle:)`, `background(_:in:fillStyle:)`, `background(in:fillStyle:)`, `background(_:in:fillStyle:)`
 --> input:1:170
1 | …ThermostatStyles], [[content: "circle"]]}], "fill:blue" => [{:fill, [file:…
  |                      ^

error: unexpected input
 --> input:1:16
1 | %{"circle" => [{:background, [file: "/Users/bcardarella/projects/lvn_demo/l…
  |                ^ expected "]"

in stylesheet:

%{"circle" => [{:background, [file: "/Users/bcardarella/projects/lvn_demo/lib/lvn_demo_web/styles/thermostat_styles.ex", line: 6, module: LvnDemoWeb.ThermostatStyles], [[content: "circle"]]}], "fill:blue" => [{:fill, [file: "/Users/bcardarella/projects/lvn_demo/lib/lvn_demo_web/styles/thermostat_styles.ex", line: 10, module: LvnDemoWeb.ThermostatStyles], [{:., [file: "/Users/bcardarella/projects/lvn_demo/lib/lvn_demo_web/styles/thermostat_styles.ex", line: 10, module: LvnDemoWeb.ThermostatStyles], [nil, :blue]}]}], "fill:white" => [{:fill, [file: "/Users/bcardarella/projects/lvn_demo/lib/lvn_demo_web/styles/thermostat_styles.ex", line: 14, module: LvnDemoWeb.ThermostatStyles], [{:., [file: "/Users/bcardarella/projects/lvn_demo/lib/lvn_demo_web/styles/thermostat_styles.ex", line: 14, module: LvnDemoWeb.ThermostatStyles], [nil, :white]}]}]}
```

Stylesheet:

```elixir
  ~SHEET"""
  "circle" do
    background(content: "circle")
  end

  "fill:blue" do
    fill(.blue)
  end

  "fill:white" do
    fill(.white)
  end
  """
```

In this case `background(content: "circle")` should be `background(content: :circle)`

When errors happen the styelsheet should irgnore gracefully and continue to the next rule

However, in this case I think when the named argument is used a `String` is acceptable. I believe we previously discussed this and landed on `atom` when using an implied content. I'd have to go back and check but it feels like this is going to be a common mistake.

### Library Version

main

### Xcode Version

latest

### Swift Version

_No response_

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

latest iOS

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by carson-katri**
Depends on #1191 

Also closes #1184

### CODE REVIEW

File: Sources/LiveViewNativeStylesheet/Parsing/External/Metadata.swift [hunk 1]
```diff
@@ -4,42 +4,56 @@ public struct Metadata {
...
+                Whitespace()
+                StringLiteral()
+                
+                Whitespace()
+                
+                "]".utf8
+            }
+            "[]".utf8.map {
+                Self.init(file: "", line: 0, module: "", source: "")
             }
```
Comment (carson-katri) [inline Sources/LiveViewNativeStylesheet/Parsing/External/Metadata.swift:56]: @bcardarella mentioned that production builds pass an empty metadata component. This should account for that, but let me know if there is any other data passed besides an empty list literal `[]`.

Comment (NduatiK) [reply Sources/LiveViewNativeStylesheet/Parsing/External/Metadata.swift:56]: This is correct for the modifier metadata.

**Review by NduatiK — APPROVED** [review]
LGTM!
